[General]
;The Game's name you want to log to log file.
;Supported games: Honkai: Star Rail, Genshin Impact, Honkai Impact 3rd
;GameName = Honkai: Star Rail
;GameName = Genshin Impact
;GameName = Honkai Impact 3rd
GameName = Honkai: Star Rail
;The output folder name you want to use.
;For Honkai: Star Rail:
OutputFolder = C:/Program Files/Star Rail/Game/Mods/output/
;For Genshin Impact:
;OutputFolder = C:/Program Files/Genshin Impact/Genshin Impact Game/Mods/output/
;For Honkai Impact 3rd:
;OutputFolder = C:/Program Files/Honkai Impact 3rd/Games/Mods/output/
;Here is your Loader location or where your d3d11.dll located at.
;For Honkai: Star Rail:
LoaderFolder = C:/Program Files/Star Rail/Game/
;For Genshin Impact:
;LoaderFolder = C:/Program Files/Genshin Impact/Genshin Impact Game/
;For Honkai Impact 3rd:
;LoaderFolder = C:/Program Files/Honkai Impact 3rd/Games/
;Whether to delete output folder before execute script
DeleteOutputFolder = True
;Set work dir, here is your FrameAnalysis dump dir.
FrameAnalyseFolder = FrameAnalysis-2023-05-06-181056
;Set your mod name
mod_name = heita_v1

[Merge]
;The index buffer hash you select from game.
draw_ib = 5186a9b8
;Name the part you want to merge vb files, note this will be your output mod's prefix.
part_name = body
;Control the element you want to extract from vb0 file.
;It also control the final vb0's vertex-data's order.
;element_list = POSITION,NORMAL,TANGENT,COLOR,TEXCOORD,BLENDWEIGHTS,BLENDINDICES
element_list = POSITION,NORMAL,TANGENT,COLOR,TEXCOORD,TEXCOORD1,BLENDWEIGHTS,BLENDINDICES
;What kinds of merge process you want to choose:"weapon","cloth","body" etc.
;(Now only "weapon" and others)
type = cloth
;Here is the ROOT VS the game currently use, HSR use e8425f64cfb887cd as it's ROOT ACTION VS now.
;Unity 2019.4 LTS use these values even between games.
;RootActionVS = e8425f64cfb887cd  for body hair face cloth etc. but sometimes weapon also use this.
;RootItemVS = 9684c4091fc9e35a    for weapon,static object etc.
root_vs = e8425f64cfb887cd
;Whether to use pointlist tech,because some game do not use pointlist tech. True or False
use_pointlist = True
;Whether to only collect vertex-data from pointlist tech files,
;in GIMI,texcoord info is collected from the object being first draw completely to screen to make sure it's correct.
;but collect it from pointlist is much easier,and they may have different logic to draw in game.
;in some game,the texcoord info from pointlist and trianglelist is different ,some is same.
only_pointlist = True
;the .ib file's format,normally will be
ib_format = DXGI_FORMAT_R16_UINT

[Split]
;Which algorithm to recalculate the TANGENT value.
;Because these game do not put real TANGENT in the tangent slot,it put something else
;looks like is another DIY type of NORMAL value,so the TANGENT value need to be fix.
;now there is 2 value can be select:  simple, nearest
repair_tangent = simple


